### ISSUE TITLE
Nullpointer whenever no mankini is found

### ISSUE THREAD

**Issue by Mrbysco** [Mrbysco/Mankini#1]
> Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
	at net.minecraft.entity.player.InventoryPlayer.removeStackFromSlot(InventoryPlayer.java:537) ~[InventoryPlayer.class:?]
	at matgm50.mankini.item.ItemMankiniCannon.onItemRightClick(ItemMankiniCannon.java:51) ~[ItemMankiniCannon.class:?]
	at net.minecraft.item.ItemStack.useItemRightClick(ItemStack.java:176) ~[ItemStack.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.processRightClick(PlayerInteractionManager.java:391) ~[PlayerInteractionManager.class:?]
	at net.minecraft.network.NetHandlerPlayServer.processPlayerBlockPlacement(NetHandlerPlayServer.java:740) ~[NetHandlerPlayServer.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItem.processPacket(CPacketPlayerTryUseItem.java:43) ~[CPacketPlayerTryUseItem.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItem.processPacket(CPacketPlayerTryUseItem.java:9) ~[CPacketPlayerTryUseItem.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:15) ~[PacketThreadUtil$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_111]
	at net.minecraft.util.Util.runTask(Util.java:25) ~[Util.class:?]
	... 5 more

**Comment by Mrbysco** [comment]
I believe I fixed this after I found this
